# Generated by Django 3.2.25 on 2024-04-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0034_cash_in_hand_cashinhandtransactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='balance',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate_items',
            name='hsn',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='estimate_items',
            name='tax',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='PartyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=20)),
                ('transactiondate', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.party')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details')),
            ],
        ),
        migrations.CreateModel(
            name='Item_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=20)),
                ('transactiondate', models.DateField(auto_now=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details')),
            ],
        ),
    ]
