# Generated by Django 3.2.25 on 2024-05-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0038_remove_banktransactionmodel_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactionmodel',
            name='from_bank_current_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransactionmodel',
            name='to_bank_current_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
